spring:
  datasource:
    username: root
    password: 'smzn68032136..'
    url: jdbc:mysql://localhost:3306/db_nft?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.163.com
    username: paul990323@163.com
    password: GZADDJBZGSPISWNY    #  w163:GZADDJBZGSPISWNY    qq:tmpbcnorvqjqbfhd
    default-encoding: utf-8
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 8
        max-wait: 10000
    timeout: 5000
  application:
    name: myNFT-server
  boot:
    admin:
      client:
        url: http://127.0.0.1:8888

server:
  port: 8080

logging:
  file:
    name: admin-server.log

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: '*'



# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    return-instance-for-empty-row: true



